### ISSUE TITLE
Issue with SARI scores

### ISSUE THREAD

**Issue by roemmele** [feralvam/easse#62]
Hi, thanks for making this available! I'm running the corpus_sari() function according to your example and I'm seeing some oddness with the scores. For example, system sentences without any token overlap with the source or references are being scored higher than those with overlap. Here's an example of a sentence without overlap:

```python
corpus_sari(orig_sents=["About 95 species are currently accepted ."],
            sys_sents=["This is my simplified sentence that has no token overlap with the source or reference sentences."], 
            refs_sents=[["About 95 species are currently known .", "About 95 species are now accepted .",  "95 species are now accepted ."]])                                                                            
Out[4]: 19.246031746031743
```
Whereas I get a lower score for this sentence that does have overlap:

```python
corpus_sari(orig_sents=["About 95 species are currently accepted ."], 
            sys_sents=["species accepted ."], 
            refs_sents=[["About 95 species are currently known .",  "About 95 species are now accepted .", "95 species are now accepted ."]])                                                                            
Out[5]: 16.402116402116405
```
I get different results using the code in https://github.com/XingxingZhang/pysari that also implements SARI: ~16.078 for my first example system sentence above and ~24.05 for the second example, which is the score ordering I'd expect though I haven't verified the correctness of anything. Is there a parameter setting that needs to be specified when calling the corpus_sari() function that's affecting the results? Thanks!

**Comment by feralvam** [comment]
Hi @roemmele,

Thanks for using EASSE on your research. My apologies, but the example in the README has not been updated according to the latest version of the package. 

For your particular example, since you are only evaluating one sentence, I'd recommend using `sentence_sari` instead of `corpus_sari`. In addition, I'd recommend making it explicit that the input is already tokenized, so that EASSE doesn't try to do it internally.  

```python
sentence_sari(orig_sent="About 95 species are currently accepted .",  
              sys_sent="This is my simplified sentence that has no token overlap with the source or reference sentences.", 
              ref_sents=["About 95 species are currently known .", "About 95 species are now accepted .",  "95 species are now accepted ."], 
              tokenizer='none')
Out[2]: 16.078042328042326

sentence_sari(orig_sent="About 95 species are currently accepted .",  
              sys_sent="species accepted .", 
              ref_sents=["About 95 species are currently known .", "About 95 species are now accepted .",  "95 species are now accepted ."], 
              tokenizer='none')
Out[3]: 24.175824175824175
```

If you'd still like to use `corpus_sari` for just one sentence, the calls should be:

```python
corpus_sari(orig_sents=["About 95 species are currently accepted ."],  
            sys_sents=["This is my simplified sentence that has no token overlap with the source or reference sentences."], 
            refs_sents=[["About 95 species are currently known ."], ["About 95 species are now accepted ."],  ["95 species are now accepted ."]], 
            tokenizer='none', use_f1_for_deletion=False)
Out[4]: 16.078042328042326

corpus_sari(orig_sents=["About 95 species are currently accepted ."],  
            sys_sents=["species accepted ."], 
            refs_sents=[["About 95 species are currently known ."], ["About 95 species are now accepted ."],  ["95 species are now accepted ."]], 
            tokenizer='none', use_f1_for_deletion=False)
Out[5]: 24.175824175824175
```
It's important to notice that `corpus_sari` calculates a *system-level* score. As such, you should set `use_f1_for_deletion=True` (the default value) so that it behaves in the same way as the original JAVA implementation that's used in almost all papers to compute the score at the system-level. The original Python implementation (like in https://github.com/XingxingZhang/pysari) is for *sentence-level* SARI, and as such the deletion operation should be calculated using only precision. This is transparent in EASSE: if you are calculating the sentence-level score (i.e. only one sentence) use `sentence_sari`, if you are going to calculate the system-level score use `corpus_sari`. We take care of setting `use_f1_for_deletion` in the most adequate way.  

Also, notice how the references are passed to `corpus_sari`. I'll provide another example with more sentences for better illustration:

```python
corpus_sari(orig_sents=["About 95 species are currently accepted .", "The cat perched on the mat ."],  
            sys_sents=["species accepted .", "cat on mat ."], 
            refs_sents=[["About 95 species are currently known .", "The cat sat on the mat ."],
                        ["About 95 species are now accepted .", "The cat is on the mat ."],  
                        ["95 species are now accepted .", "The cat sat ."]])
```
I hope this helps. If you have any more issues or require clarifications, please let us know.

**Comment by roemmele** [comment]
Oh, I see. Ok, I will try that, thank you!
