### ISSUE TITLE
Difference between easse and huggingface/datasets SARI computation

### ISSUE THREAD

**Issue by alisonhc** [feralvam/easse#98]
Hello, can someone help me understand the difference between EASSE and huggingface/datasets SARI computation? Using the defaults for both libraries, I see aa 3-6 point discrepancy on the ASSET benchmark for some models I fine-tuned.

I understand that EASSE has `use_f1_for_deletion=True` as its default, and datasets uses precision. But with `use_f1_for_deletion` set to False in EASSE, I still see a small difference in SARI score (~0.6) between the two libraries.

Thanks!

**Comment by louismartin** [comment]
Hi and thank you for the issue.

That's a good question, we are not familiar with the SARI implementation on Huggingface as it seems it was implemented recently.

@ddhruvkr can you maybe help here?

**Comment by alisonhc** [comment]
Thank you! Do you think that change makes the SARI score more accurate? Would be a useful change in this repo as well?

**Comment by ddhruvkr** [comment]
I think it depends on the task and the dataset. For scenarios, where the source and target are rarely the same and you want to test the model's ability to recognize this case and make no change, this HF implementation is fine. However, I tried the HF implementation on a text editing task where for a lot of cases the src and target were similar. There, the problem was that this implementation favoured models that that made little to no change on almost all the documents, which is problematic.

**Comment by alisonhc** [comment]
That makes sense! Will keep that in mind.
